# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clone for faster checkout

      - name: Set up Python 3.10
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: '3.10'
          cache: 'pip'  # Enable pip cachin

      - name: Install dependencies
        run: |
          # python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install Playwright browsers
        run: | 
          python -m playwright install chromium --with-deps
      - name: Test with pytest
        run: |
          xvfb-run -a pytest -v